# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5db7edc8eb3b70e97813ee8419d31762dc80a1a8abc544da307a268c71da95c1f5b6cdf88cbffcc4585528eb6cc94f9b671cbe0d40f6948d0c3b1c8f8c896bee

test:
  secret_key_base: 326934a57aafee03a0cfaed059098796f0a369cb7665fd8089d378c49d2c48a45677b2d3b9ec70eef95fcc3d4d75efa01d1a96aa465b881b2c637f1c04600e5f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: ba1c5c6ba9254f2e8f02dacbdc53acc7dab0db671609783889cbb73c9fb3144855d7203ac043b13efb4aec1cbb1b8dc500979c882b91f47e535b487c24b619a5
  VAPID_PUBLIC_KEY: BLkuGusxjLlZdYSi0pk1RoMdVQbK6AEsdNej2RwVG9iRgdti0VTju1qZXic-wW72EfbzwrpLsqmdgPjrxEV58mw=
  VAPID_PRIVATE_KEY: l1dfTrdJPbZvJCh9Awg5dyhAnxiGuASp9jfsU1vI928=
  #5db7edc8eb3b70e97813ee8419d31762dc80a1a8abc544da307a268c71da95c1f5b6cdf88cbffcc4585528eb6cc94f9b671cbe0d40f6948d0c3b1c8f8c896beo